version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptofollow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/cryptofollow}
      JWT_SECRET: ${JWT_SECRET:-change-me}
      BASE_CURRENCY: ${BASE_CURRENCY:-EUR}
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:${PORT:-3000}}
    environment:
      NODE_ENV: production
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - backend

volumes:
  pgdata:
